export const ARTICLE_SET_ACTIVE = 'ARTICLE_SET_ACTIVE';
export const ARTICLES_RECEIVE = 'ARTICLES_RECEIVE';
export const ARTICLES_REQUEST = 'ARTICLES_REQUEST';
export const ARTICLES_REQUEST_FAILURE = 'ARTICLES_REQUEST_FAILURE';

export const SETTINGS_UPDATE_SETTING = 'SETTINGS_UPDATE_SETTING';

export const SITE_SET_ACTIVE = 'SITE_SET_ACTIVE';